"""Add video_link column to lessons table

Revision ID: 457857de2395
Revises: 31748d11b4d1
Create Date: 2025-11-25 11:48:57.476821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '457857de2395'
down_revision = '31748d11b4d1'
branch_label = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('video_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'video_link')
    # ### end Alembic commands ###
