"""add_lesson_fields

Revision ID: ef17fdf2e3b0
Revises: fix_teacher_id_type
Create Date: 2025-11-10 06:18:55.019477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef17fdf2e3b0'
down_revision = 'fix_teacher_id_type'
branch_label = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add new lesson fields; skip dropping retinify_users, alter_column for courses and lesson_progress
    op.add_column('lessons', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('lessons', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('lessons', sa.Column('duration_text', sa.String(length=50), nullable=True))
    op.add_column('lessons', sa.Column('quizzes_json', sa.JSON(), nullable=True))
    op.add_column('lessons', sa.Column('assignments_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'assignments_json')
    op.drop_column('lessons', 'quizzes_json')
    op.drop_column('lessons', 'duration_text')
    op.drop_column('lessons', 'status')
    op.drop_column('lessons', 'description')
    # ### end Alembic commands ###
